FROM mcr.microsoft.com/playwright:v1.47.2-focal

WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install Node.js dependencies
RUN npm ci

# Copy the rest of your application code
COPY . .

# Set the default command
CMD ["npx", "playwright", "test"]
