FROM ruby:3.2.2

RUN useradd -m circleci

WORKDIR /app/backend

# Copy Gemfile and Gemfile.lock first to leverage Docker layer caching
COPY Gemfile Gemfile.lock ./

# Install dependencies
RUN bundle install

# Copy the rest of the application code
COPY . .

CMD ["bash"]
